### ISSUE TITLE
Would be easier to set up if you had a Gemfile. 

### ISSUE THREAD

**Issue by W3NDO** [TimoKats/inspyr#1]
I want to open a PR to fix this issue. What is your collaboration strategy?

**Comment by TimoKats** [comment]
Hi W3NDO, thanks for you interest in inspyr. Preferably fork the repo and issue a pull request (which I'm very likely to accept :)). Is that ok? I can also add you as a collaborator if you prefer that.

**Comment by W3NDO** [comment]
I forked the Repo and opened the PR.

**Comment by kaspergrubbe** [comment]
Why did you delete these changes in the main branch?

**Comment by W3NDO** [comment]
There were version issues with the Gemfile.
