### ISSUE TITLE
invalid byte sequence in US-ASCII error

### ISSUE THREAD

**Issue by W3NDO** [TimoKats/inspyr#2]
I am getting this Sinatra error `invalid byte sequence in US-ASCII`  when I try to add a node through the automated suggestions. I'm running on Kubuntu 22.04 & ruby:2.7

**Comment by TimoKats** [comment]
Hello. That's strange. My suspicion is that `corpus.txt` has some non-ascii characters. I'll look into this. Do you get this error every time you run the app?

PS: I'm running `ruby 3.1.2` on `windows`.

**Comment by W3NDO** [comment]
Yes, I get this error everytime I run the app. 

I will try changing my ruby environment to 3.1.2 and see if the error persists.
